// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'th'

export type Locales =
	| 'en'
	| 'th'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * ช​ื​่​อ​ผ​ู​้​ใ​ช​้​ง​า​น
		 */
		username: string
		/**
		 * อ​ี​เ​ม​ล​์
		 */
		email: string
		/**
		 * ร​ห​ั​ส​ผ​่​า​น
		 */
		password: string
		/**
		 * ย​ื​น​ย​ั​น​ร​ห​ั​ส​ผ​่​า​น
		 */
		passwordConfirm: string
		/**
		 * เ​ข​้​า​ส​ู​่​ร​ะ​บ​บ
		 */
		login: string
		/**
		 * ส​ม​ั​ค​ร​ส​ม​า​ช​ิ​ก
		 */
		register: string
		reset: {
			/**
			 * ร​ี​เ​ซ​็​ท
			 */
			main: string
		}
	}
	/**
	 * ส​ว​ั​ส​ด​ี​ ​{​n​a​m​e​}​!
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	validation: {
		/**
		 * อ​ี​เ​ม​ล​ล​์​ไ​ม​่​ถ​ู​ก​ต​้​อ​ง
		 */
		invalidEmail: string
		/**
		 * ก​ร​ุ​ณ​า​ร​ะ​บ​ุ​{​f​i​e​l​d​}
		 * @param {string} field
		 */
		required: RequiredParams<'field'>
		min: {
			/**
			 * ก​ร​ุ​ณ​า​ร​ะ​บ​ุ​{​n​a​m​e​}​อ​ย​่​า​ง​น​้​อ​ย​ ​{​m​i​n​}​ ​ต​ั​ว​อ​ั​ก​ษ​ร
			 * @param {number} min
			 * @param {string} name
			 */
			string: RequiredParams<'min' | 'name'>
		}
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * ชื่อผู้ใช้งาน
		 */
		username: () => LocalizedString
		/**
		 * อีเมล์
		 */
		email: () => LocalizedString
		/**
		 * รหัสผ่าน
		 */
		password: () => LocalizedString
		/**
		 * ยืนยันรหัสผ่าน
		 */
		passwordConfirm: () => LocalizedString
		/**
		 * เข้าสู่ระบบ
		 */
		login: () => LocalizedString
		/**
		 * สมัครสมาชิก
		 */
		register: () => LocalizedString
		reset: {
			/**
			 * รีเซ็ท
			 */
			main: () => LocalizedString
		}
	}
	/**
	 * สวัสดี {name}!
	 */
	HI: (arg: { name: string }) => LocalizedString
	validation: {
		/**
		 * อีเมลล์ไม่ถูกต้อง
		 */
		invalidEmail: () => LocalizedString
		/**
		 * กรุณาระบุ{field}
		 */
		required: (arg: { field: string }) => LocalizedString
		min: {
			/**
			 * กรุณาระบุ{name}อย่างน้อย {min} ตัวอักษร
			 */
			string: (arg: { min: number, name: string }) => LocalizedString
		}
	}
}

export type Formatters = {}
